apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy:
    canary:
      maxUnavailable: 1
      maxSurge: 1
      steps:
        - setWeight: 20
        - pause:
            duration: 30s  # pause for 30 seconds after 20% traffic
        - setWeight: 50
        - pause:
            duration: 30s  # pause for 30 seconds after 50% traffic
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: mueljr/argo-rollouts-demo:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31393
