apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
  namespace: demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setReplicas: 1       # Start with 1 pod (20% of 5)
      - pause: {duration: 30s}
      - setReplicas: 3       # 3 pods (60% of 5)
      - pause: {duration: 30s}
      - setReplicas: 5       # Full rollout
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: mueljr/argo-rollouts-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
spec:
  selector:
    app: demo
  ports:
  - port: 80
    targetPort: 8080
